### ISSUE TITLE
Should the package depend on libboost?

### ISSUE THREAD

**Issue by gavanderhoorn** [StefanFabian/qml_ros2_plugin#2]
**Describe the bug**

Build in a clean `ros:galactic` container fails with a "no such file or directory" error from the compiler complaining about `boost/endian/conversion.hpp`.

**To Reproduce**
1. start a `ros:galactic` container
2. clone this repository and `LOEWE-emergenCITY/ros2_babel_fish` into a workspace
3. use `rosdep install ...` to install dependencies
4. attempt to build the workspace
5. observe compiler complaining about missing file

**Expected behavior**
Build should succeed.

**Comment by gavanderhoorn** [comment]
I believe the cause is this:

https://github.com/StefanFabian/qml_ros2_plugin/blob/7f445a949e9fe1051450f2fea60204a71f32a430/src/image_buffer.cpp#L20

`image_buffer.cpp` directly `#include`s the boost header, but the manifest does not state that dependency.

---

Edit: if you agree, I could submit a PR adding the `libboost-dev` dependency.

**Comment by StefanFabian** [comment]
Hm, I'd rather not depend on boost just for one method.
It didn't matter in ROS1 since ROS itself depended on boost anyway.
I will look into this. Thank you for bringing it to my attention!
