### ISSUE TITLE
Displaying a robot in qml/qml-urdf importer

### ISSUE THREAD

**Issue by luisa223** [StefanFabian/qml_ros2_plugin#5]
For my use case, I would like to display a full robot model on the qml UI. Do you have any experience with that or could you think of a way on how to do this? So far, I did not find similar projects or a real starting point for this feature.

**Comment by StefanFabian** [comment]
Unfortunately, no; I think the easiest solution would be to integrate librviz and use a RenderPanel with the robotstate display to render the robot model.
But I'm not sure how well this is supported with rviz2 (yet).
I have only done this as a 2D representation to visualize the flipper angles not a full robot.
![grafik](https://github.com/user-attachments/assets/c9983242-8aaa-45cd-b985-418e13128924)
